# Generated by Django 5.1.5 on 2025-02-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('Course', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=4)),
                ('Experience', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Begginer', max_length=30)),
                ('Phone', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=30)),
                ('Student_ID', models.CharField(max_length=12)),
            ],
        ),
    ]
