# Generated by Django 4.2.16 on 2024-11-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registerpages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('years_of_experience', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('About_Python', models.CharField(max_length=100)),
            ],
        ),
    ]
