<<<<<<< HEAD
# Generated by Django 5.1.5 on 2025-02-27 15:33
=======
# Generated by Django 4.2.16 on 2024-11-29 04:45
>>>>>>> backend

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='RegisterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('Course', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=4)),
                ('Experience', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Begginer', max_length=30)),
                ('Phone', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=30)),
                ('Student_ID', models.CharField(max_length=12)),
=======
            name='registerpages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('years_of_experience', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('About_Python', models.CharField(max_length=100)),
>>>>>>> backend
            ],
        ),
    ]
