# Generated by Django 4.2.16 on 2024-11-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mzumbepycon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerpages',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
    ]
